# .github/workflows/feed-check.yml
name: Feed Validation

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Check Feed Validity
        run: |
          npm install -g feed-validator
          feed-validator https://cpf-coaching.com/feed.xml