name: RSS Feed Update

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:

jobs:
  rss-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm init -y
          npm install @extractus/feed-extractor@latest dompurify jsdom node-fetch@3

      - name: Create output directory
        run: mkdir -p _rss_posts

      - name: Parse Feeds
        run: node scripts/parse-feeds.js

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rss-posts
          path: _rss_posts/

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update RSS feed content'
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
