name: RSS Feed Update

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:

jobs:
  rss-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install @extractus/feed-extractor
          npm install dompurify jsdom

      - name: Parse Feeds
        run: |
          const fs = require('fs');
          const path = require('path');
          const { extract } = require('@extractus/feed-extractor');
          const createDOMPurify = require('dompurify');
          const { JSDOM } = require('jsdom');
          const window = new JSDOM('').window;
          const DOMPurify = createDOMPurify(window);

          const parserOptions = {
            getExtraEntryFields: (feedType) => {
              if (feedType === 'json') return ['external_url'];
              if (feedType === 'atom') return ['summary'];
              return [];
            }
          };

          const feedUrls = [
            'https://cpfcoaching.com/feed.xml',
            'https://example.com/rss'
          ];

          async function processFeeds() {
            for (const url of feedUrls) {
              const feed = await extract(url, parserOptions);
              feed.items.forEach(item => {
                // Robust date parsing
                const pubDate = new Date(item.pubDate || item.published || item.date);

                // Content sanitization
                const dirtyContent = item.content;
                const cleanContent = DOMPurify.sanitize(dirtyContent, {
                  ALLOWED_TAGS: ['p', 'a', 'em', 'strong'],
                  ALLOWED_ATTR: ['href']
                });

                // Path sanitization
                const safeFilename = path.basename(item.id) + '.md';
                const filepath = path.join('_rss_posts', safeFilename);

                const frontmatter = `---
title: "${item.title}"
date: ${pubDate.toISOString()}
external_url: "${item.link}"
---\n\n${cleanContent}`;
                fs.writeFileSync(filepath, frontmatter);
              });
            }
          }

          processFeeds();

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update RSS feed content'
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
