name: Update RSS Feeds

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:        # Allow manual triggers

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm ci
          
      - name: Create posts directory
        run: |
          mkdir -p _rss_posts
          
      - name: Update RSS feeds
        run: |
          node scripts/parse-feeds.js
          
      - name: Debug directory content
        run: |
          echo "Current directory contents:"
          ls -la
          echo "RSS posts directory contents:"
          ls -la _rss_posts/
          
      - name: Upload RSS posts artifact
        uses: actions/upload-artifact@v4
        with:
          name: rss-posts
          path: _rss_posts/
          if-no-files-found: warn
          
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Update RSS feeds and blog posts" || echo "No changes to commit"
          git push || echo "No changes to push"