name: Update RSS Feeds

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:        # Allow manual triggers

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm ci
          
      - name: Update RSS feeds
        run: |
          node scripts/parse-feeds.js
          
      - name: Check for changes
        id: git-check
        run: |
          git status --porcelain
          echo "::set-output name=modified::$(if git status --porcelain | grep .; then echo "true"; else echo "false"; fi)"
          
      - name: Commit changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Update RSS feeds and blog posts"
          git push
          
      - name: No changes found
        if: steps.git-check.outputs.modified == 'false'
        run: echo "No changes to commit"